chats/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers
from . import views
from .views import (
					ChatGroupViewSet, UserViewSet, 
					TopicViewSet, LocalChatViewSet, 
					GlobalChatViewSet, ProfileViewSet
					)


# Configuring the router
router = routers.DefaultRouter()
router.register('chatgroups', ChatGroupViewSet)
router.register('users', UserViewSet)
router.register('topics', TopicViewSet)
router.register('localchats', LocalChatViewSet)
router.register('globalchats', GlobalChatViewSet)
router.register('profiles', ProfileViewSet)

# Attaching the urlconf generated by the rounter to the urlpatterns	
urlpatterns = router.urls

fractal/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf import settings
from django.views.static import serve
from django.conf.urls.static import static
from django.conf.urls import include
from rest_framework_jwt.views import obtain_jwt_token, refresh_jwt_token, verify_jwt_token
# from chats.api.views import FacebookLogin, FacebookConnect
# from rest_auth.registration.views import (
#     SocialAccountListView, SocialAccountDisconnectView
# )


# Have a separate module for the accounts

urlpatterns = [
	url(r'^admin/', admin.site.urls),

	#url(r'^accounts/', include('allauth.urls')),

	url(r'^api/', include('chats.api.urls'), name="api"),

	url(r'^api/realtime/', include('interactive.api.urls'), name="api_messaging"),

	url(r'^rest-auth/', include('rest_auth.urls')),

	# url(r'^rest-auth/registration/', include('rest_auth.registration.urls')),

	url(r'^api/auth/token', obtain_jwt_token),

	url(r'^api-token-refresh/', refresh_jwt_token),

	url(r'^api-token-verify/', verify_jwt_token),

	# url(r'^rest-auth/facebook/$', FacebookLogin.as_view(), name='fb_login'),

	# url(r'^rest-auth/facebook/connect/$', FacebookConnect.as_view(), name='fb_connect'),

 #    url(r'^socialaccounts/$', SocialAccountListView.as_view(), name='social_account_list'),

 #    url(r'^socialaccounts/(?P<pk>\d+)/disconnect/$', SocialAccountDisconnectView.as_view(), name='social_account_disconnect'),    	
]

interactive/archive/urls.py
urlpatterns = [



  #url(r'^user_notifications/$', user_notifications, name='user_notifications'),


  #url(r'^single/post/$', single_post, name='single_post'),



]

chats/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from datetime import datetime
from django.urls import reverse
import interactive
from .utilities import unique_label_generator
from allauth.account.models import EmailAddress
from django.contrib.staticfiles.templatetags.staticfiles import static

# The packages needed for ranking purposes 
from datetime import datetime, timedelta
from math import log

#from .managers import TopicManager

from django.utils.timezone import make_aware
from django.utils import timezone



User = settings.AUTH_USER_MODEL


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    followers = models.ManyToManyField(User, blank=True, related_name="is_following")
    about = models.CharField(max_length=200, blank=True)
    avatar = models.ImageField(upload_to="profile_avatar", blank=True)

    timestamp = models.DateTimeField(auto_now_add=True)


    def account_verified(self): # Checks if the user's email address has been verified
        if self.user.is_authenticated:
            result = EmailAddress.objects.filter(email=self.user.email)
            if len(result):
                return result[0].verified
        return False



    def get_number_of_followers(self):
        return self.followers.count()

    def get_number_of_following(self):
        return self.user.is_following.count()


    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('profile', kwargs={'pk': self.pk})

    def get_absolute_url_for_avatar(self):
        #print(self.avatar is None)
        if not self.avatar:
            #print("This user has not provided an avatar")

            try:

                #return reverse("static", kwargs={'path': "chats/default-img/default-user.jpg"})
                return static('chats/default-img/default-user.jpg')

            except:
                import sys
                print(str(sys.exc_info()))    

        else:
            #print(self.avatar)
            #return  reverse("media", kwargs={'path': self.avatar})
            return self.avatar.url



    def get_absolute_url_followers(self):

        return reverse("profile-followers", kwargs={'pk': self.pk})


    def get_absolute_url_following(self):
        return reverse("profile-following", kwargs={'pk': self.pk})

    def get_absolute_url_chatgroups(self):

        return reverse("profile-chatgroups", kwargs={'pk': self.pk})






def post_save_user_receiver(sender, instance, created, *args, **kwargs):
    if created:
        profile, is_created = Profile.objects.get_or_create(user=instance)

post_save.connect(post_save_user_receiver, sender=User)



class ChatGroup(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    about = models.CharField(max_length=200)
    members = models.ManyToManyField(User, related_name="is_member")
    timestamp = models.DateTimeField(auto_now_add=True)
    avatar = models.ImageField(upload_to="group_avatar", blank=True)
    label = models.SlugField(unique=True)

    def get_number_of_members(self):
        return self.members.count()

    def get_absolute_url_for_avatar(self):



        if not self.avatar:
            #print("This chatgroup doesn't have an avatar yet")
            try:
                #return reverse("static", kwargs={'path': "chats/default-img/default-chatgroup.jpg"})
                return static("chats/default-img/default-chatgroup.jpg")

            except:
                import sys
                print(str(sys.exc_info()))    

        else:
            #return  reverse("media", kwargs={'path': self.avatar})
            return self.avatar.url



    def get_owner(self):
        return self.owner


    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('chatgroup-detail', kwargs={'pk': self.pk})








class Topic(models.Model):
    chatgroup = models.ForeignKey(ChatGroup, on_delete=models.CASCADE)  # the parent chat group
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    about = models.CharField(max_length=200)
    is_hidden = models.BooleanField(default=False)
    is_private = models.BooleanField(default=False)
    arrow_ups = models.ManyToManyField(User, related_name='arrow_ups')
    arrow_downs = models.ManyToManyField(User, related_name='arrow_downs')
    avatar = models.ImageField(upload_to="topic_avatar", blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    label = models.SlugField(unique=True)

    current_participants = models.ManyToManyField(User, related_name='topic_current')



    


    # Ranking functions below, trensfer those functions into a model manager!

    def get_short_about(self):
        return self.about[0:25]


    def epoch_seconds(self):
        
        epoch = datetime(1970, 1, 1)
        epoch = make_aware(epoch, timezone.get_default_timezone())
        td = self.timestamp - epoch
        print(td)
        return td.days * 86400 + td.seconds + (float(td.microseconds) / 1000000)




    def score(self):
        print(self.arrow_ups.count() - self.arrow_downs.count())
        return (self.arrow_ups.count() - self.arrow_downs.count())


    def trending(self):
        score = self.score()
        print(score)

        order = log(max(abs(score), 1), 10)
        if score > 0:
            sign = 1
        elif score < 0:
            sign = -1
        else:
            sign = 0    

        seconds = self.epoch_seconds() - 1134028003

        final_rank = round(sign * order + seconds / 45000, 7)

        print("The final rank of " + self.name + " is " + str(final_rank))
        return round(sign * order + seconds / 45000, 7)



    # End of the ranking functions    

    def get_name(self):
        return self.name


    def get_owner(self):
        return self.owner.id


    def get_chatgroup_owner(self):
        return self.chatgroup.owner


    def __str__(self):
        return self.name


    def get_room_type(self):
        return "Topic"

    def get_absolute_url(self):
        return reverse('chatroom', kwargs={'chat_room_type': 'topic', "label": self.label})

    def get_topic_rating(self):
        return self.arrow_ups.count() - self.arrow_downs.count()


    def get_the_most_recent_message(self):

        list_of_messages = self.topic_messages.filter(flag__isnull=True).order_by('-timestamp')[:1]

        if len(list_of_messages) == 0:
            #print("There is no messages in the local chat")
            top_message = None


        else:
            top_message = list_of_messages[0]

            # Shorten the string if necessary to fit two lines, do it as a method for the message

            print(top_message.text)

        return top_message

    def get_absolute_url_for_avatar(self):
        if not self.avatar:
            try:
                #return reverse("static", kwargs={'path': "chats/default-img/default-topic.png"})
                return static("chats/default-img/default-topic.png")
            except:
                import sys
                print(str(sys.exc_info()))    

        else:
            #return  reverse("media", kwargs={'path': self.avatar})
            return self.avatar.url

            
        




'''  Implementing the slug generator for the topic


def pre_save_topic_receiver(sender, instance, created, *args, **kwargs):
    if not instance.label:
        print("Making a label for the topic")
        instance.label = unique_label_generator(instance)


post_save.connect(pre_save_topic_receiver, sender=Topic)


'''




class LocalChat(models.Model):
    chatgroup = models.ForeignKey(ChatGroup, on_delete=models.CASCADE) # the parent chat group
    name = models.CharField(max_length=200)
    about = models.CharField(max_length=200)
    is_hidden = models.BooleanField(default=False)
    is_private = models.BooleanField(default=False)
    avatar = models.ImageField(upload_to="local_chat_avatar", blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    participants = models.ManyToManyField(User, related_name="is_participant")
    label = models.SlugField(unique=True)
    current_participants = models.ManyToManyField(User, related_name='localchat_current')


    def get_name(self):
        return self.name

    def get_owner(self):
        return self.chatgroup.owner.id

    def get_room_type(self):
        return "Local Chat"

    def get_absolute_url_for_avatar(self):
        if not self.avatar:
            try:
                #return reverse("static", kwargs={'path': "chats/default-img/default-localchat.png"})
                return static("chats/default-img/default-localchat.png")
            except:
                import sys
                print(str(sys.exc_info()))    

        else:
            #return  reverse("media", kwargs={'path': self.avatar})
            return self.avatar.url

    def get_absolute_url(self):
        return reverse('chatroom', kwargs={'chat_room_type': 'localchat', "label": self.label})


    def get_number_of_participants(self):
        return self.participants.count()


    def get_the_most_recent_message(self):

        list_of_messages = self.localchat_messages.filter(flag__isnull=True).order_by('-timestamp')[:1]

        if len(list_of_messages) == 0:
            #print("There is no messages in the local chat")
            top_message = None


        else:
            top_message = list_of_messages[0]
            print(top_message.text)

        return top_message


    def __str__(self):
        return self.name



class GlobalChat(models.Model):
    chatgroup = models.OneToOneField(ChatGroup, on_delete=models.CASCADE) # the parent chat group -> one to one relationship
    label = models.SlugField(unique=True)

chats/models/chatgroup.py
from django.db import models
from django.conf import settings
from rest_framework.reverse import reverse as api_reverse


User = settings.AUTH_USER_MODEL

class ChatGroup(models.Model):
	owner 		= models.ForeignKey(User, on_delete=models.CASCADE)
	name 		= models.CharField(max_length=200, blank=False)
	about 		= models.CharField(max_length=200, blank=True)
	description = models.TextField(blank=True)
	members 	= models.ManyToManyField(User, blank=True, related_name="is_member")

	timestamp 	= models.DateTimeField(auto_now_add=True)

	avatar 		= models.ImageField(upload_to="chatgroup_avatar", blank=True, null=True)

	label 		= models.SlugField(unique=True, blank=False) # unique way to name a chatgroup in the url

	# methods will be added later
	def __str__(self):
		return self.name

	def followers_count(self):
		return self.members.count()	
		
	def topics_count(self):
		return self.topic_chatgroup.all().count()

	def localchats_count(self):
		return self.localchat_chatgroup.all().count()	

	def ownerProfile(self):
		return self.owner.profile

	# not elegant -> defo change implementation	
	def followers(self):
		followers = []
		for follower in self.members.all():
			followers.append(follower.profile)
		
		return followers

chats/models/globalchat.py
from django.db import models
from django.conf import settings
from .chatgroup import ChatGroup
from django.db.models.signals import post_save
from .utilities import unique_label_generator

User = settings.AUTH_USER_MODEL


class GlobalChat(models.Model):
    
    chatgroup 			= models.OneToOneField(ChatGroup, on_delete=models.CASCADE)
    label 				= models.SlugField(unique=True)
    online_participants = models.ManyToManyField(User, blank=True, related_name='globalchat_online_participants')
    saves 				= models.ManyToManyField(User, blank=True, related_name='globalchat_saves')

    @property
    def owner(self):
        return self.chatgroup.user

# Signal that generates a new GlobalChat when a Chatgroup is created
def post_save_chatgroup_receiver(sender, instance, created, *args, **kwargs):

	if created:

		chatgroup_label = unique_label_generator(instance)
		instance.label = chatgroup_label
		instance.save()
		globalchat, is_created = GlobalChat.objects.get_or_create(chatgroup=instance, label=instance.label)


post_save.connect(post_save_chatgroup_receiver, sender=ChatGroup)

chats/models/globalchats.py
class GlobalChat(models.Model):
    
    chatgroup 			= models.OneToOneField(ChatGroup, on_delete=models.CASCADE) # the parent chat group -> one to one relationship
    label 				= models.SlugField(unique=True)
    online_participants = models.ManyToManyField(User, related_name='globalchat_online_participants')

chats/models/localchat.py
from django.db import models
from .chatgroup import ChatGroup
from django.conf import settings
from rest_framework.reverse import reverse as api_reverse
User = settings.AUTH_USER_MODEL


class LocalChat(models.Model):
    chatgroup = models.ForeignKey(ChatGroup, on_delete=models.CASCADE, related_name="localchat_chatgroup")  # the parent chat group
    name = models.CharField(max_length=200)
    about = models.CharField(max_length=200, blank=True)
    description = models.TextField(blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to="localchat_avatar", blank=True)

    saves = models.ManyToManyField(User, blank=True, related_name="localchat_saves")
    timestamp = models.DateTimeField(auto_now_add=True)
    label = models.SlugField(unique=True) # Unique way to name a topic/localchat in the URL

    online_participants = models.ManyToManyField(User, blank=True, related_name="localchat_online")


    def __str__(self):
        return self.name

    # def get_api_url(self, request=None):
    #     return api_reverse("localchat-rud", kwargs={"pk":self.pk}, request=request)
            

    

    # need to fully undertand how the related_name attribute functions
    # is_hidden and is_private will be added later
    # No methods for now -> need to pin down the structure of the database tables


    #class Meta:
        #abstract=True

chats/models/signals.py
# Signales should be moved here

interactive/models/postcomment.py
from django.db import models
from chats.models import ChatGroup, LocalChat, Topic, GlobalChat
from django.conf import settings
from .message import Message
from .post import Post

User = settings.AUTH_USER_MODEL




class PostComment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    text = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    likers = models.ManyToManyField(User, blank=True, related_name="comment_likers")
    dislikers = models.ManyToManyField(User, blank=True, related_name="comment_dislikers")

chats/archive/templates/chats/NewChatGroup.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>SignUp</title>




	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" type="text/css" href="{% static "chats/css/bootstrap.css" %}"  />
	<link rel="stylesheet" type="text/css" href="{% static "chats/css/main.css" %}" />
  
</head>
<body>

<div class="container">


	<div class="fractal_brend">



		<span>New Chat Group</span>


	</div>


	<div class="sign_in">


		<form enctype="multipart/form-data" method="post" action="/foo/">{% csrf_token %}





			{% for field in form %}
			<div class="form-group">
      <p>

        {{ field }}



        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
		</div>
    {% endfor %}

	<button type="submit">Create</button>























		</form>





	
	</div>




</div>


</body>
</html>

chats/archive/templates/chats/chatgroup_search.html
{% extends 'chats/base.html' %}



{% block title %} Chatgroup Search {% endblock %}




{% block content %}




{% for object in search_results %}





    <div class="c-g-i">


      <div class="pull-left">

      <a href="{{object.get_absolute_url}}"><img class="img-circle" src="{{object.get_absolute_url_for_avatar}}"></a>


      </div>

      <div class="info">


      <div class="main-info">

      <h4> <a href="{{object.get_absolute_url}}"> {{object.name}} </a>



     <!-- <input id="follow_chatgroup" type="button" name="{{object.id}}" class="follow-btn-big btn" value="Follow" /> -->


      <!--<button class="follow_chatgroup follow-btn-big btn"> Follow </button> -->


     <!-- <input id="chatgroup_id" type="hidden" value="{{object.id}}" /> -->


      <a id="follow_big{{object.id}}" class="afollow_search_list follow-btn-big btn" href="#" data-id="{{ object.id }}">



          {% if request.user in object.members.all %}

            Unfollow


            {% else %}


            Follow


          {% endif %}





      </a>




      </h4>

      <button id="follow_small{{object.id}}" class="afollow_search_list follow_chatgroup follow-btn btn" data-id="{{object.id}}">


      {% if request.user in object.members.all %}

          Unfollow


          {% else %}


          Follow


      {% endif %}





      </button>






      </div>

      <div class="clear"> </div>

      <div class="other-info">

        <div class="group-stats">

        <span class="followers"> <span id="follower_counter{{object.id}}"> {{object.members.count}} </span> followers </span>
        <span class="local-chats"> <span> {{object.localchat_set.count}} </span> local chats </span>
        <span class="topics"> <span> {{object.topic_set.count}} </span> topics </span>

        </div>


        <div class="group-about">
          <p>


            {{object.about}}
          </p>

        </div>

      </div>


      <div class="clear-medium"> </div>
      </div>




    </div>










{% endfor %}









{% endblock %}

chats/archive/templates/chats/chatgroupcreate.html
{% extends 'chats/base.html' %}



{% block title %} Create a new ChatGroup {% endblock %}




{% block content%}





    <h2 class="new_group_page_title">New Chat Group</h2>






  <div class="new_chatgroup">
	<form method="post" enctype="multipart/form-data">{% csrf_token %}





			{% for field in form %}
			<div class="form-group">
      <p>

        {{ field }}



        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
		</div>
    {% endfor %}

    <div class="input_new_chatgroup form-group">

      <button class="upload_chatgroup_photo btn btn-primary" type="button" class="btn btn-primary"> Upload a Photo </button>
      <span class="photo_location">  </span>

    </div>

    <div class="input_new_chatgroup form-group">

	   <button type="submit" class="button_black_bg btn btn-primary">Create</button>

    </div> 




</form>
</div>


{% endblock %}

chats/archive/templates/chats/chatgrouplist.html
{% extends 'chats/base.html' %}



{% block title %} Create a new ChatGroup {% endblock %}




{% block content %}



<h1> List of Chat Groups</h1>


<ul>


{% for chat_group in object_list%}


   <li>  {{chat_group.name}}</li>








{% endfor %}





</ul>


{% endblock %}

chats/archive/templates/chats/profile.html
{% extends 'chats/base.html' %}
{% load staticfiles %}




{% block title %} {{object.user.username}} {% endblock %}




{% block content %}





	<div class="row">

		<div class="col-xs-1"> </div>

		<div class="col-xs-10 text-center">

			<img class="avatar img-circle" src="{{object.get_absolute_url_for_avatar}}">
			<h2 class="username"> {{object.user.username}}</h2>
			<h4 class="user_describtion"> {{object.about}} </h4>



			{% if request.user.id == object.user.id %}

			<h4 class="user_describtion"><button class="edit_profile_button btn" type="button" data-toggle="modal" data-target=".editProfile"> Edit Profile </button></h4>

			{% else %}



			<button id="follow_a_user_{{object.id}}" class="follow_a_user follow-btn-big btn" data-id="{{object.id}}">



				{% if is_following %}

				Unfollow

				{% else %}

				Follow

				{% endif %}


			</button>
			<button id="follow_a_user_small_{{object.id}}" class="follow_a_user follow-btn btn" data-id="{{object.id}}">

				{% if is_following %}

				Unfollow

				{% else %}

				Follow

				{% endif %}



			</button>



			{% endif %}





		</div>


		<div class="col-xs-1"> </div>



		<div class="col-xs-12 col-md-6">

			<div class="user_stats">

					<span class="number">{{posts.count}}</span> <span>  posts</span>
					<a href="{{object.get_absolute_url_chatgroups}}"> <span class="number"> {{chatgroups.count}} </span> <span>  chat groups</span> </a>

			</div>

		</div>


		<div class="col-xs-12 col-md-6">

			<div class="user_stats">


				<a data-id="{{object.id}}" class="show_modal show_followers_modal" role="button"><span id="profile_id_{{object.id}}" class="number">{{object.get_number_of_followers}} </span> <span> followers</span> </a>
				<a data-id="{{object.id}}" class="show_modal show_following_modal" role="button"><span class="number">{{object.get_number_of_following}} </span> <span> following</span> </a>

			</div>

		</div>













	</div>



	<div class="row">
		<div class="col-xs-1"> </div>


		<div class="col-xs-10">

			{% for post in posts %}
			<div class="user_post">

			<a class="pull-left">
				<img class="img-circle" src="{{object.get_absolute_url_for_avatar}}" height="30px" width="30px">

			</a>

			<div class="user_post_content">

			<span class="username_small">{{post.message.user.username}}</span>

				<a href="


				{% if post.message.chatgroup %}
				{{post.message.chatgroup.get_absolute_url}}
				{% else %}

				#

				{% endif %}


				"><span class="chat_name_small">{{post.message.chatgroup.name}}</span> </a>

			<a href="{{post.message.get_absolute_url_room}}"> <span class="context">Context</span> </a>

			<p id="user_message_{{post.id}}" class="user_message">

			{% if post.message.get_message_type == "text" %}

			{{post.message.short_text|urlize}}

			{% if post.message.longer_than_144 %}

			<a href="#" data-id="{{post.id}}" class="display_rest_of_post" style="color: #999 !important; "> more </a>

			{% endif %}
			<!-- When making the post shorter, how to deal with the more button --> 


			{% else %}

			<img class="uploaded_image_post uploaded_chat_image" src="{{post.message.photo.url}}">

			{% endif %}




			</p>


			<div class="likes_comments">


				<!--<span class="heart glyphicon glyphicon-heart"> </span>-->


				<button type="button" name="{{post.id}}" class="post_like_button fa" >

								{% if request.user in post.likers.all %}

								<i class="post_like red_heart fa fa-heart" aria-hidden="true"></i>

								

								{% else %}

								<i class="post_like fa fa-heart-o" aria-hidden="true"></i>

								

								{% endif %}

				</button>



				<a data-id="{{post.id}}" class="show_who_liked" href="#" role="button"><span id="{{post.id}}" style="margin-left: 2px;" class="number_of_likes"> {{post.get_number_of_likes}}</span> likes</a>




				<a data-id={{post.id}} class="input_link" id="input_link_{{post.id}}" role="button" href="#"  ><span class="comment_icon glyphicon glyphicon-comment">  </span></a>
				<span id="number_of_comments_{{post.id}}">{{post.get_number_of_comments}}</span>


				<span class="time_uploaded"> {{post.timestamp}} </span>

				<!--
				<div class="comments">
				{% for comment in post.postcomment_set.all %}


					<span class="username_small">{{comment.user.username}}</span>
					<span class="user_message"> {{post.message.text}} </span>





				{%endfor%}

				</div>
				-->




				<div id="post_comments_{{post.id}}" class="post_comments"> 

				{% for post_comment in post.postcomment_set.all|dictsort:"timestamp"|slice:"0:2" %}



				
				<div class="a_comment">  


					<a href="{{post_comment.user.profile.get_absolute_url}}"><span class="username_comment_small">{{post_comment.user.username}}</span> </a>


					<span class="comment_text"> {{post_comment.text}}</span>

					<!-- The like button should be here -->


					<button id="post_commnet_like_button_{{post_comment.id}}" type="button" name="{{post_comment.id}}" class="post_comment_like_button fa" >

								{% if request.user in post_comment.likers.all %}

								<i class="post_comment_like red_heart fa fa-heart" aria-hidden="true"></i>

								

								{% else %}

								<i class="post_comment_like fa fa-heart-o" aria-hidden="true"></i>

								

								{% endif %}

					</button>



				<!--<a data-id="{{post_comment.id}}" class="" href="#" role="button">--><span id="post_comment_{{post_comment.id}}" style="margin-left: 2px;" class="number_of_likes"> {{post_comment.get_number_of_likes}}</span><!--</a>-->




				</div>


				{% endfor%}


				</div>
				{% if post.get_number_of_comments > 2 %}

				<a id="load_more_{{post.id}}" data-id="{{post.id}}" class="load_more_comments" href="#" role="button"> Load more comments </a>

				{% endif %}

				<hr class="divides_comments_from_input">

				<div class="input_a_comment">

					<form method="post" data-id="{{post.id}}" class="add_a_comment_form" >
					{%csrf_token%}

						<div class="form-group">

							<input id="input_comment_{{post.id}}" type="text" name="comment_text" class="comment_input form_control" placeholder="Add a comment">

						</div>


					</form>


				</div>






				<!--<hr> -->

			</div>













			</div>



			</div>




			{% endfor %}


		</div>
		<div class="col-xs-1"> </div>


	</div>






{% if request.user.id == object.user.id %}
<div id="{{object.id}}" class="editProfile modal" role="dialog">
									  <div class="modal-dialog modal-lg">

										<!-- Modal content-->
											<div class="modal-content">


												<div class="modal-header">
													<button type="button" class="close" data-dismiss="modal"> &times; </button>
													<h4 class="modal-title"> <span id="username"> {{object.user.username}} </span></h4>
												</div>


											  <div class="modal-body">

											  		<form action="/edit_profile/{{object.id}}/" method="post" enctype="multipart/form-data">{% csrf_token %}


													


														<div class="form-group">

															<label for="editUsername"> Username </label>
															<input type="text" class="form-control" id="editUsername" name="username" aria-describedby="changename" value="{{object.user.username}}">

													  	</div>


														<div class="form-group">

															<label for="editAbout"> About </label>
															<input type="text" class="form-control" id="editAbout" name="about" aria-describedby="changename" value="{{object.about}}">

													  	</div>




													  	<div class="form-group">

													  	
													  			<label for="editAvatar"> Edit Profile Pic </label>

													  			<input type="file" class="form-control-file" id="editAvatar" name="avatar" value="">
															

													  	</div>

													  	 

														<button type="submit" class="btn btn-default">Submit</button>




													</form>



											  </div>

											  <!--<div class="modal-footer">
												<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
											  </div> -->
										</div>

								  </div>
</div>

{% endif %}












<div class="modal fade profile_modal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
  

</div>



<div class="modal fade post_likers" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">

<!-- A container for the likers of a specific post --> 

</div>















{% endblock %}


{% block bodylast %}


<input id="userURL" type="hidden" value="{{object.get_absolute_url}}" />








{% endblock %}

chats/archive/templates/chats/profile_chatgroups.html
{% extends 'chats/base.html' %}



{% block title %} New Topic {% endblock %}




{% block content%}


{% for chatgroup in chatgroups %}


<a href="{{chatgroup.get_absolute_url}}"> {{chatgroup.name}} </a></br>





{% endfor %}


{% endblock %}